name: Upload Assets

on:
  push:
    branches:
      - upload-to-s3

#on:
#  release:
#    types: [published]

jobs:
  trigger-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger workflow in private repository
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TAG: "2.2.2"
          ASSET: ${{ github.event.repository.name }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $ACCESS_TOKEN" \
          https://api.github.com/repos/kaltura/ovp-statboy/actions/workflows/upload-assets-to-s3-express-recorder.yaml/dispatches \
          -d "{\"ref\":\"master\",\"inputs\":{\"tag\":\"$TAG\",\"asset\":\"$ASSET\"}}"